### PR TITLE
Tests and data

### PR DESCRIPTION
**Pull request by nslay**
Sorry for the delay Matthew. The streaming test does not appear to work on FreeBSD even though requested regions are being handled correctly. This may be an OpenSlide issue.

I will check against Windows and Linux.

### CODE REVIEW

**Comment by thewtex** [comment]
@nslay Looking great!  Even without streaming, this is a a very useful feature!

After merged, you will want to rebase your future work on the upstream master and use a topic branch for future pull requests.  That will look something like this:

```
cd /path/to/ITKIOOpenSlide/
git checkout master
git remote add upstream https://github.com/InsightSoftwareConsortium/ITKIOOpenSlide.git
git fetch upstream
git reset --hard upstream/master
git checkout -b myNextTopicName
```

**Comment by nslay** [comment]
I see the problem with streaming.
Check this out:
http://openslide.org/api/openslide_8h.html#a0eeecec682efdf2ef18c8426109acad0

> x The top left x-coordinate, **in the level 0 reference frame.**
> y The top left y-coordinate, **in the level 0 reference frame.**

So some very careful handling is needed. I need to make `GenerateStreamableReadRegionFromRequestedRegion` do something special now.

My current thinking is using something like GCD on level 0 and current level dimensions and then ensuring the read region is a multiple of the denominator of the downsample factor. Can you think of a more efficient way to do this?

On another point, I get a crash using OpenSlide functions in VS 2010. Although OpenSlide works with VS 2015. I noticed that if I change linking to generate Debug symbols, then everything works. Maybe MingW libraries like to resolve their own symbols or something odd? I'm at a loss on this one.

**Comment by thewtex** [comment]
Cool.

Yes, it sounds tricky. That approach sounds good.  Note that we have itk::Math::GreatestPrimeFactor if it comes in useful:

  http://www.itk.org/Doxygen/html/namespaceitk_1_1Math.html#a40e9c17433e8e93421029de845355c78

I recommend building OpenSlide from source with the same compiler that ITK was built with. C++ does not have compatibility across compilers or even with the same compiler if libraries are built with different flags.

**Comment by nslay** [comment]
Ah, nice to know. I saw ITK has vnl_rational and started to use that.

What is preferred when presented with the option of using ITK or VNL
mathematical functionality?

**Comment by thewtex** [comment]
If ITK interfaces are present, they are preferred, then VNL.

**Comment by nslay** [comment]
The elaborate solution that uses vnl_rational gives an identical image to
just reading the whole thing at once. But it causes 200 divisions to become
2 divisions.
Worst case scenario is that you have two prime dimensions.

I examined the openslide code. It splits the image up into 4096x4096 parts.
The vendor-specific code simply divides by downsample factor to downsample
the level 0 coordinates. Other parts of the code simply multiply and floor
when upsampling coordinates.

I think I'll just multiply and floor by the downsample factor too. But then
the resulting image is slightly different. I can't explain why they're
different given how openslide internally handles these coordinates. Maybe
Cairo or ITK does some kind of averaging or interpolation on the boundaries
or something like that? The different pixel intensities don't appear
locally anywhere in the original image. So an inconsistency in coordinates
doesn't seem to be the likely cause.

**Comment by thewtex** [comment]
Hmm, interesting.  ITK does not treat region boundaries differently when streaming.

**Comment by nslay** [comment]
Nice that the testing framework generates some kind of difference image. I
uploaded them here if you're curious:
https://midas3.kitware.com/midas/folder/13510

Not sure what to make of the diff image. Sometimes it has non-zero pixels
when the intensities are the same. Most of the large differences are in the
blobs.

**Pull request merged**
