### PR TITLE
Add wrapping and a streaming example.

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
CC: @cdeepakroy

**Comment by cdeepakroy** [comment]
@thewtex this is neat :). I'll try using it.

Would be nice to do a computational time + memory performance benchmarking for images of varying sizes.

**Comment by cdeepakroy** [comment]
CC: @brianhelba

**Comment by nslay** [comment]
I'm less savvy with Python. Looks good to me though!

**Pull request merged**
